# Generated by Django 4.1.5 on 2023-01-26 20:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdskUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('adsk_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='signs/')),
                ('adsk_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adsk_handler.adskuser')),
            ],
        ),
    ]
