# Generated by Django 4.1.5 on 2023-01-27 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adsk_handler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdskProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('adsk_id', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='adskuser',
            name='adsk_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.CreateModel(
            name='GeneralContractor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('adsk_project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adsk_handler.adskproject')),
            ],
        ),
    ]
