# Generated by Django 4.1.5 on 2023-01-27 15:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adsk_handler', '0002_adskproject_alter_adskuser_adsk_id_generalcontractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('documentName', models.CharField(max_length=200)),
                ('lType', models.CharField(choices=[('QRC', 'QR code'), ('STA', 'Stamp')], max_length=200)),
                ('added', models.BooleanField(default=False)),
                ('reviewId', models.CharField(max_length=200)),
                ('approvalDate', models.DateField()),
                ('resourceUrn', models.CharField(max_length=200)),
                ('approverUserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsk_handler.adskuser')),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adsk_handler.adskproject')),
            ],
        ),
    ]
