# Generated by Django 4.1.5 on 2023-01-27 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adsk_handler', '0003_logincident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logincident',
            old_name='approverUserId',
            new_name='approverUser',
        ),
        migrations.RenameField(
            model_name='logincident',
            old_name='projectId',
            new_name='project',
        ),
    ]
