# Generated by Django 4.1.5 on 2023-02-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsk_handler', '0004_rename_approveruserid_logincident_approveruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logincident',
            name='approvedResourceUrn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
