# Generated by Django 4.1.5 on 2023-02-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adsk_handler', '0005_logincident_approvedresourceurn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adskuser',
            name='adsk_id',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adskuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adskuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adskuser',
            name='job_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adskuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
