version: "3.9"
services:
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    container_name: stamps_web
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

  db:
    image: postgres:13
    container_name: stamps_db
    volumes:
      - stamps_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
volumes:
  stamps_data:
